/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/http/src/http_module';
import * as import8 from '@angular/router/src/router_module';
import * as import9 from '../modules/a/a.module';
import * as import10 from '../modules/b/b.module';
import * as import11 from '../modules/c/c.module';
import * as import12 from '@angular/common/src/localization';
import * as import13 from '@angular/core/src/application_init';
import * as import14 from '@angular/core/src/testability/testability';
import * as import15 from '@angular/core/src/application_ref';
import * as import16 from '@angular/core/src/linker/compiler';
import * as import17 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import18 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import19 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import20 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import21 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import22 from '@angular/core/src/linker/view_utils';
import * as import23 from '@angular/platform-browser/src/browser/title';
import * as import24 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import25 from '@angular/http/src/backends/browser_xhr';
import * as import26 from '@angular/http/src/base_response_options';
import * as import27 from '@angular/http/src/backends/xhr_backend';
import * as import28 from '@angular/http/src/base_request_options';
import * as import29 from './app.service';
import * as import30 from '@angular/common/src/location/location';
import * as import31 from '@angular/router/src/url_tree';
import * as import32 from '@angular/router/src/router_outlet_map';
import * as import33 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import34 from '@angular/core/src/di/injector';
import * as import35 from '../modules/a/a.component.ngfactory';
import * as import36 from '../modules/b/b.component.ngfactory';
import * as import37 from '../modules/c/c.component.ngfactory';
import * as import38 from '../modules/c/d.component.ngfactory';
import * as import39 from './app.component.ngfactory';
import * as import40 from './pagenotfound.component.ngfactory';
import * as import41 from '@angular/core/src/application_tokens';
import * as import42 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import43 from '@angular/platform-browser/src/dom/events/key_events';
import * as import44 from '@angular/core/src/zone/ng_zone';
import * as import45 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import46 from '../modules/a/a.component';
import * as import47 from '../modules/b/b.component';
import * as import48 from '../modules/c/c.component';
import * as import49 from '../modules/c/d.component';
import * as import50 from './app.component';
import * as import51 from './pagenotfound.component';
import * as import52 from '@angular/common/src/location/platform_location';
import * as import53 from '@angular/common/src/location/location_strategy';
import * as import54 from '@angular/router/src/router';
import * as import55 from '@angular/core/src/console';
import * as import56 from '@angular/core/src/i18n/tokens';
import * as import57 from '@angular/core/src/error_handler';
import * as import58 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import59 from '@angular/platform-browser/src/dom/animation_driver';
import * as import60 from '@angular/core/src/render/api';
import * as import61 from '@angular/core/src/security';
import * as import62 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import63 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import64 from '@angular/http/src/interfaces';
import * as import65 from '@angular/http/src/http';
import * as import66 from '@angular/router/src/router_config_loader';
import * as import67 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import68 from '@angular/router/src/router_state';
import * as import69 from '@angular/core/src/i18n/tokens';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _HttpModule_5:import7.HttpModule;
  _ROUTER_FORROOT_GUARD_6:any;
  _RouterModule_7:import8.RouterModule;
  _AModule_8:import9.AModule;
  _BModule_9:import10.BModule;
  _CModule_10:import11.CModule;
  _AppModule_11:import1.AppModule;
  __LOCALE_ID_12:any;
  __NgLocalization_13:import12.NgLocaleLocalization;
  _ErrorHandler_14:any;
  _ApplicationInitStatus_15:import13.ApplicationInitStatus;
  _Testability_16:import14.Testability;
  _ApplicationRef__17:import15.ApplicationRef_;
  __ApplicationRef_18:any;
  __Compiler_19:import16.Compiler;
  __APP_ID_20:any;
  __DOCUMENT_21:any;
  __HAMMER_GESTURE_CONFIG_22:import17.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_23:any[];
  __EventManager_24:import18.EventManager;
  __DomSharedStylesHost_25:import19.DomSharedStylesHost;
  __AnimationDriver_26:any;
  __DomRootRenderer_27:import20.DomRootRenderer_;
  __RootRenderer_28:any;
  __DomSanitizer_29:import21.DomSanitizerImpl;
  __Sanitizer_30:any;
  __ViewUtils_31:import22.ViewUtils;
  __IterableDiffers_32:any;
  __KeyValueDiffers_33:any;
  __SharedStylesHost_34:any;
  __Title_35:import23.Title;
  __RadioControlRegistry_36:import24.RadioControlRegistry;
  __BrowserXhr_37:import25.BrowserXhr;
  __ResponseOptions_38:import26.BaseResponseOptions;
  __XSRFStrategy_39:any;
  __XHRBackend_40:import27.XHRBackend;
  __RequestOptions_41:import28.BaseRequestOptions;
  __Http_42:any;
  __ROUTES_43:any[];
  __AppService_44:import29.AppService;
  __ROUTER_CONFIGURATION_45:any;
  __LocationStrategy_46:any;
  __Location_47:import30.Location;
  __UrlSerializer_48:import31.DefaultUrlSerializer;
  __RouterOutletMap_49:import32.RouterOutletMap;
  __NgModuleFactoryLoader_50:import33.SystemJsNgModuleLoader;
  __Router_51:any;
  __ActivatedRoute_52:any;
  __APP_BOOTSTRAP_LISTENER_53:any[];
  __TRANSLATIONS_FORMAT_54:any;
  constructor(parent:import34.Injector) {
    super(parent,[
      import35.AComponentNgFactory,
      import35.AaComponentNgFactory,
      import35.AbComponentNgFactory,
      import35.AcComponentNgFactory,
      import36.BComponentNgFactory,
      import36.BaComponentNgFactory,
      import36.BbComponentNgFactory,
      import36.BcComponentNgFactory,
      import36.BComponentNgFactory,
      import37.CComponentNgFactory,
      import37.CaComponentNgFactory,
      import37.CbComponentNgFactory,
      import38.DComponentNgFactory,
      import38.DaComponentNgFactory,
      import38.DbComponentNgFactory,
      import39.DefaultComponentNgFactory,
      import40.PageNotFoundComponentNgFactory,
      import39.AppComponentNgFactory
    ]
    ,[import39.AppComponentNgFactory]);
  }
  get _LOCALE_ID_12():any {
    if ((this.__LOCALE_ID_12 == (null as any))) { (this.__LOCALE_ID_12 = (null as any)); }
    return this.__LOCALE_ID_12;
  }
  get _NgLocalization_13():import12.NgLocaleLocalization {
    if ((this.__NgLocalization_13 == (null as any))) { (this.__NgLocalization_13 = new import12.NgLocaleLocalization(this._LOCALE_ID_12)); }
    return this.__NgLocalization_13;
  }
  get _ApplicationRef_18():any {
    if ((this.__ApplicationRef_18 == (null as any))) { (this.__ApplicationRef_18 = this._ApplicationRef__17); }
    return this.__ApplicationRef_18;
  }
  get _Compiler_19():import16.Compiler {
    if ((this.__Compiler_19 == (null as any))) { (this.__Compiler_19 = new import16.Compiler()); }
    return this.__Compiler_19;
  }
  get _APP_ID_20():any {
    if ((this.__APP_ID_20 == (null as any))) { (this.__APP_ID_20 = import41._appIdRandomProviderFactory()); }
    return this.__APP_ID_20;
  }
  get _DOCUMENT_21():any {
    if ((this.__DOCUMENT_21 == (null as any))) { (this.__DOCUMENT_21 = import4._document()); }
    return this.__DOCUMENT_21;
  }
  get _HAMMER_GESTURE_CONFIG_22():import17.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_22 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_22 = new import17.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_22;
  }
  get _EVENT_MANAGER_PLUGINS_23():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_23 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_23 = [
      new import42.DomEventsPlugin(),
      new import43.KeyEventsPlugin(),
      new import17.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_22)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_23;
  }
  get _EventManager_24():import18.EventManager {
    if ((this.__EventManager_24 == (null as any))) { (this.__EventManager_24 = new import18.EventManager(this._EVENT_MANAGER_PLUGINS_23,this.parent.get(import44.NgZone))); }
    return this.__EventManager_24;
  }
  get _DomSharedStylesHost_25():import19.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_25 == (null as any))) { (this.__DomSharedStylesHost_25 = new import19.DomSharedStylesHost(this._DOCUMENT_21)); }
    return this.__DomSharedStylesHost_25;
  }
  get _AnimationDriver_26():any {
    if ((this.__AnimationDriver_26 == (null as any))) { (this.__AnimationDriver_26 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_26;
  }
  get _DomRootRenderer_27():import20.DomRootRenderer_ {
    if ((this.__DomRootRenderer_27 == (null as any))) { (this.__DomRootRenderer_27 = new import20.DomRootRenderer_(this._DOCUMENT_21,this._EventManager_24,this._DomSharedStylesHost_25,this._AnimationDriver_26)); }
    return this.__DomRootRenderer_27;
  }
  get _RootRenderer_28():any {
    if ((this.__RootRenderer_28 == (null as any))) { (this.__RootRenderer_28 = import45._createConditionalRootRenderer(this._DomRootRenderer_27,this.parent.get(import45.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_28;
  }
  get _DomSanitizer_29():import21.DomSanitizerImpl {
    if ((this.__DomSanitizer_29 == (null as any))) { (this.__DomSanitizer_29 = new import21.DomSanitizerImpl()); }
    return this.__DomSanitizer_29;
  }
  get _Sanitizer_30():any {
    if ((this.__Sanitizer_30 == (null as any))) { (this.__Sanitizer_30 = this._DomSanitizer_29); }
    return this.__Sanitizer_30;
  }
  get _ViewUtils_31():import22.ViewUtils {
    if ((this.__ViewUtils_31 == (null as any))) { (this.__ViewUtils_31 = new import22.ViewUtils(this._RootRenderer_28,this._APP_ID_20,this._Sanitizer_30)); }
    return this.__ViewUtils_31;
  }
  get _IterableDiffers_32():any {
    if ((this.__IterableDiffers_32 == (null as any))) { (this.__IterableDiffers_32 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_32;
  }
  get _KeyValueDiffers_33():any {
    if ((this.__KeyValueDiffers_33 == (null as any))) { (this.__KeyValueDiffers_33 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_33;
  }
  get _SharedStylesHost_34():any {
    if ((this.__SharedStylesHost_34 == (null as any))) { (this.__SharedStylesHost_34 = this._DomSharedStylesHost_25); }
    return this.__SharedStylesHost_34;
  }
  get _Title_35():import23.Title {
    if ((this.__Title_35 == (null as any))) { (this.__Title_35 = new import23.Title()); }
    return this.__Title_35;
  }
  get _RadioControlRegistry_36():import24.RadioControlRegistry {
    if ((this.__RadioControlRegistry_36 == (null as any))) { (this.__RadioControlRegistry_36 = new import24.RadioControlRegistry()); }
    return this.__RadioControlRegistry_36;
  }
  get _BrowserXhr_37():import25.BrowserXhr {
    if ((this.__BrowserXhr_37 == (null as any))) { (this.__BrowserXhr_37 = new import25.BrowserXhr()); }
    return this.__BrowserXhr_37;
  }
  get _ResponseOptions_38():import26.BaseResponseOptions {
    if ((this.__ResponseOptions_38 == (null as any))) { (this.__ResponseOptions_38 = new import26.BaseResponseOptions()); }
    return this.__ResponseOptions_38;
  }
  get _XSRFStrategy_39():any {
    if ((this.__XSRFStrategy_39 == (null as any))) { (this.__XSRFStrategy_39 = import7._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_39;
  }
  get _XHRBackend_40():import27.XHRBackend {
    if ((this.__XHRBackend_40 == (null as any))) { (this.__XHRBackend_40 = new import27.XHRBackend(this._BrowserXhr_37,this._ResponseOptions_38,this._XSRFStrategy_39)); }
    return this.__XHRBackend_40;
  }
  get _RequestOptions_41():import28.BaseRequestOptions {
    if ((this.__RequestOptions_41 == (null as any))) { (this.__RequestOptions_41 = new import28.BaseRequestOptions()); }
    return this.__RequestOptions_41;
  }
  get _Http_42():any {
    if ((this.__Http_42 == (null as any))) { (this.__Http_42 = import7.httpFactory(this._XHRBackend_40,this._RequestOptions_41)); }
    return this.__Http_42;
  }
  get _ROUTES_43():any[] {
    if ((this.__ROUTES_43 == (null as any))) { (this.__ROUTES_43 = [
        [{
          path: 'a',
          component: import46.AComponent,
          children: [
            {
              path: 'a',
              component: import46.AaComponent
            }
            ,
            {
              path: 'b',
              component: import46.AbComponent
            }
            ,
            {
              path: 'c',
              component: import46.AcComponent
            }

          ]

        }
      ],
        [{
          path: 'b',
          component: import47.BComponent,
          canActivate: [import29.AppService],
          canActivateChild: [import29.AppService],
          canLoad: [import29.AppService],
          canDeactivate: [import29.AppService],
          children: [
            {
              path: '',
              redirectTo: 'a',
              pathMatch: 'full'
            }
            ,
            {
              path: 'a',
              component: import47.BaComponent
            }
            ,
            {
              path: 'b',
              component: import47.BbComponent
            }
            ,
            {
              path: 'c',
              component: import47.BcComponent
            }

          ]

        }
      ],
      [
        {
          path: 'c',
          component: import48.CComponent,
          children: [
            {
              path: '',
              redirectTo: 'a',
              pathMatch: 'full'
            }
            ,
            {
              path: 'a',
              component: import48.CaComponent
            }
            ,
            {
              path: 'b',
              component: import48.CbComponent
            }

          ]

        }
        ,
        {
          path: 'd',
          component: import49.DComponent,
          children: [
            {
              path: '',
              redirectTo: 'a',
              pathMatch: 'full'
            }
            ,
            {
              path: 'a',
              component: import49.DaComponent
            }
            ,
            {
              path: 'b',
              component: import49.DbComponent
            }

          ]

        }

      ]
      ,
      [
        {
          path: '',
          redirectTo: '/c/c',
          pathMatch: 'full'
        }
        ,
        {
          path: 'app',
          component: import50.DefaultComponent,
          canActivate: [import29.AppService],
          canActivateChild: [import29.AppService],
          canLoad: [import29.AppService],
          canDeactivate: [import29.AppService]
        }
        ,
        {
          path: '**',
          component: import51.PageNotFoundComponent
        }

      ]

    ]
    ); }
    return this.__ROUTES_43;
  }
  get _AppService_44():import29.AppService {
    if ((this.__AppService_44 == (null as any))) { (this.__AppService_44 = new import29.AppService()); }
    return this.__AppService_44;
  }
  get _ROUTER_CONFIGURATION_45():any {
    if ((this.__ROUTER_CONFIGURATION_45 == (null as any))) { (this.__ROUTER_CONFIGURATION_45 = {}); }
    return this.__ROUTER_CONFIGURATION_45;
  }
  get _LocationStrategy_46():any {
    if ((this.__LocationStrategy_46 == (null as any))) { (this.__LocationStrategy_46 = import8.provideLocationStrategy(this.parent.get(import52.PlatformLocation),this.parent.get(import53.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_45)); }
    return this.__LocationStrategy_46;
  }
  get _Location_47():import30.Location {
    if ((this.__Location_47 == (null as any))) { (this.__Location_47 = new import30.Location(this._LocationStrategy_46)); }
    return this.__Location_47;
  }
  get _UrlSerializer_48():import31.DefaultUrlSerializer {
    if ((this.__UrlSerializer_48 == (null as any))) { (this.__UrlSerializer_48 = new import31.DefaultUrlSerializer()); }
    return this.__UrlSerializer_48;
  }
  get _RouterOutletMap_49():import32.RouterOutletMap {
    if ((this.__RouterOutletMap_49 == (null as any))) { (this.__RouterOutletMap_49 = new import32.RouterOutletMap()); }
    return this.__RouterOutletMap_49;
  }
  get _NgModuleFactoryLoader_50():import33.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_50 == (null as any))) { (this.__NgModuleFactoryLoader_50 = new import33.SystemJsNgModuleLoader(this._Compiler_19,this.parent.get(import33.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_50;
  }
  get _Router_51():any {
    if ((this.__Router_51 == (null as any))) { (this.__Router_51 = import8.setupRouter(this._ApplicationRef_18,this._UrlSerializer_48,this._RouterOutletMap_49,this._Location_47,this,this._NgModuleFactoryLoader_50,this._Compiler_19,this._ROUTES_43,this._ROUTER_CONFIGURATION_45)); }
    return this.__Router_51;
  }
  get _ActivatedRoute_52():any {
    if ((this.__ActivatedRoute_52 == (null as any))) { (this.__ActivatedRoute_52 = import8.rootRoute(this._Router_51)); }
    return this.__ActivatedRoute_52;
  }
  get _APP_BOOTSTRAP_LISTENER_53():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_53 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_53 = [import8.initialRouterNavigation(this._Router_51,this._ROUTER_CONFIGURATION_45)]); }
    return this.__APP_BOOTSTRAP_LISTENER_53;
  }
  get _TRANSLATIONS_FORMAT_54():any {
    if ((this.__TRANSLATIONS_FORMAT_54 == (null as any))) { (this.__TRANSLATIONS_FORMAT_54 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_54;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._HttpModule_5 = new import7.HttpModule();
    this._ROUTER_FORROOT_GUARD_6 = import8.provideForRootGuard(this.parent.get(import54.Router,(null as any)));
    this._RouterModule_7 = new import8.RouterModule(this._ROUTER_FORROOT_GUARD_6);
    this._AModule_8 = new import9.AModule();
    this._BModule_9 = new import10.BModule();
    this._CModule_10 = new import11.CModule();
    this._AppModule_11 = new import1.AppModule();
    this._ErrorHandler_14 = import4.errorHandler();
    this._ApplicationInitStatus_15 = new import13.ApplicationInitStatus(this.parent.get(import13.APP_INITIALIZER,(null as any)));
    this._Testability_16 = new import14.Testability(this.parent.get(import44.NgZone));
    this._ApplicationRef__17 = new import15.ApplicationRef_(this.parent.get(import44.NgZone),this.parent.get(import55.Console),this,this._ErrorHandler_14,this,this._ApplicationInitStatus_15,this.parent.get(import14.TestabilityRegistry,(null as any)),this._Testability_16);
    return this._AppModule_11;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.HttpModule)) { return this._HttpModule_5; }
    if ((token === import8.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_6; }
    if ((token === import8.RouterModule)) { return this._RouterModule_7; }
    if ((token === import9.AModule)) { return this._AModule_8; }
    if ((token === import10.BModule)) { return this._BModule_9; }
    if ((token === import11.CModule)) { return this._CModule_10; }
    if ((token === import1.AppModule)) { return this._AppModule_11; }
    if ((token === import56.LOCALE_ID)) { return this._LOCALE_ID_12; }
    if ((token === import12.NgLocalization)) { return this._NgLocalization_13; }
    if ((token === import57.ErrorHandler)) { return this._ErrorHandler_14; }
    if ((token === import13.ApplicationInitStatus)) { return this._ApplicationInitStatus_15; }
    if ((token === import14.Testability)) { return this._Testability_16; }
    if ((token === import15.ApplicationRef_)) { return this._ApplicationRef__17; }
    if ((token === import15.ApplicationRef)) { return this._ApplicationRef_18; }
    if ((token === import16.Compiler)) { return this._Compiler_19; }
    if ((token === import41.APP_ID)) { return this._APP_ID_20; }
    if ((token === import58.DOCUMENT)) { return this._DOCUMENT_21; }
    if ((token === import17.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_22; }
    if ((token === import18.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_23; }
    if ((token === import18.EventManager)) { return this._EventManager_24; }
    if ((token === import19.DomSharedStylesHost)) { return this._DomSharedStylesHost_25; }
    if ((token === import59.AnimationDriver)) { return this._AnimationDriver_26; }
    if ((token === import20.DomRootRenderer)) { return this._DomRootRenderer_27; }
    if ((token === import60.RootRenderer)) { return this._RootRenderer_28; }
    if ((token === import21.DomSanitizer)) { return this._DomSanitizer_29; }
    if ((token === import61.Sanitizer)) { return this._Sanitizer_30; }
    if ((token === import22.ViewUtils)) { return this._ViewUtils_31; }
    if ((token === import62.IterableDiffers)) { return this._IterableDiffers_32; }
    if ((token === import63.KeyValueDiffers)) { return this._KeyValueDiffers_33; }
    if ((token === import19.SharedStylesHost)) { return this._SharedStylesHost_34; }
    if ((token === import23.Title)) { return this._Title_35; }
    if ((token === import24.RadioControlRegistry)) { return this._RadioControlRegistry_36; }
    if ((token === import25.BrowserXhr)) { return this._BrowserXhr_37; }
    if ((token === import26.ResponseOptions)) { return this._ResponseOptions_38; }
    if ((token === import64.XSRFStrategy)) { return this._XSRFStrategy_39; }
    if ((token === import27.XHRBackend)) { return this._XHRBackend_40; }
    if ((token === import28.RequestOptions)) { return this._RequestOptions_41; }
    if ((token === import65.Http)) { return this._Http_42; }
    if ((token === import66.ROUTES)) { return this._ROUTES_43; }
    if ((token === import29.AppService)) { return this._AppService_44; }
    if ((token === import8.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_45; }
    if ((token === import53.LocationStrategy)) { return this._LocationStrategy_46; }
    if ((token === import30.Location)) { return this._Location_47; }
    if ((token === import31.UrlSerializer)) { return this._UrlSerializer_48; }
    if ((token === import32.RouterOutletMap)) { return this._RouterOutletMap_49; }
    if ((token === import67.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_50; }
    if ((token === import54.Router)) { return this._Router_51; }
    if ((token === import68.ActivatedRoute)) { return this._ActivatedRoute_52; }
    if ((token === import41.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_53; }
    if ((token === import69.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_54; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__17.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);