/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from './app.component';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/router/src/directives/router_link';
import * as import12 from '@angular/router/src/directives/router_link_active';
import * as import13 from '@angular/router/src/directives/router_outlet';
import * as import14 from '@angular/core/src/linker/query_list';
import * as import15 from '@angular/router/src/router';
import * as import16 from '@angular/router/src/router_state';
import * as import17 from '@angular/common/src/location/location_strategy';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/router/src/router_outlet_map';
import * as import20 from '@angular/core/src/linker/component_factory_resolver';
import * as import21 from '@angular/core/src/security';
const nodeDebugInfos_AppComponent_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.AppComponent],import1.AppComponent,{})];
var renderType_AppComponent_Host:import2.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _AppComponent_0_4:import1.AppComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_AppComponent_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-app',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new import1.AppComponent();
    this._appEl_0.initComponent(this._AppComponent_0_4,[],compView_0);
    compView_0.create(this._AppComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import10.ComponentFactory<import1.AppComponent> = new import10.ComponentFactory<import1.AppComponent>('my-app',viewFactory_AppComponent_Host0,import1.AppComponent);
const styles_AppComponent:any[] = [];
const nodeDebugInfos_AppComponent0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import11.RouterLinkWithHref,
    import12.RouterLinkActive
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import11.RouterLinkWithHref,
    import12.RouterLinkActive
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import11.RouterLinkWithHref,
    import12.RouterLinkActive
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import11.RouterLinkWithHref,
    import12.RouterLinkActive
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import11.RouterLinkWithHref,
    import12.RouterLinkActive
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import11.RouterLinkWithHref,
    import12.RouterLinkActive
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import13.RouterOutlet],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_AppComponent:import2.RenderComponentType = (null as any);
class _View_AppComponent0 extends import3.DebugAppView<import1.AppComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _el_7:any;
  _RouterLinkWithHref_7_3:import11.RouterLinkWithHref;
  _RouterLinkActive_7_4:import12.RouterLinkActive;
  _query_RouterLink_7_0:import14.QueryList<any>;
  _query_RouterLinkWithHref_7_1:import14.QueryList<any>;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _el_11:any;
  _RouterLinkWithHref_11_3:import11.RouterLinkWithHref;
  _RouterLinkActive_11_4:import12.RouterLinkActive;
  _query_RouterLink_11_0:import14.QueryList<any>;
  _query_RouterLinkWithHref_11_1:import14.QueryList<any>;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _el_15:any;
  _RouterLinkWithHref_15_3:import11.RouterLinkWithHref;
  _RouterLinkActive_15_4:import12.RouterLinkActive;
  _query_RouterLink_15_0:import14.QueryList<any>;
  _query_RouterLinkWithHref_15_1:import14.QueryList<any>;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _el_19:any;
  _RouterLinkWithHref_19_3:import11.RouterLinkWithHref;
  _RouterLinkActive_19_4:import12.RouterLinkActive;
  _query_RouterLink_19_0:import14.QueryList<any>;
  _query_RouterLinkWithHref_19_1:import14.QueryList<any>;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _el_23:any;
  _RouterLinkWithHref_23_3:import11.RouterLinkWithHref;
  _RouterLinkActive_23_4:import12.RouterLinkActive;
  _query_RouterLink_23_0:import14.QueryList<any>;
  _query_RouterLinkWithHref_23_1:import14.QueryList<any>;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _el_27:any;
  _RouterLinkWithHref_27_3:import11.RouterLinkWithHref;
  _RouterLinkActive_27_4:import12.RouterLinkActive;
  _query_RouterLink_27_0:import14.QueryList<any>;
  _query_RouterLinkWithHref_27_1:import14.QueryList<any>;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import4.AppElement;
  _RouterOutlet_31_5:import13.RouterOutlet;
  _text_32:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_AppComponent0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(0,0,0));
    this._el_1 = this.renderer.createElement(parentRenderNode,'h1',this.debug(1,1,4));
    this._text_2 = this.renderer.createText(this._el_1,'Angular Router',this.debug(2,1,8));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(3,1,27));
    this._el_4 = this.renderer.createElement(parentRenderNode,'ul',this.debug(4,2,4));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',this.debug(5,2,8));
    this._el_6 = this.renderer.createElement(this._el_4,'li',this.debug(6,3,6));
    this._el_7 = this.renderer.createElement(this._el_6,'a',this.debug(7,3,10));
    this.renderer.setElementAttribute(this._el_7,'routerLink','');
    this.renderer.setElementAttribute(this._el_7,'routerLinkActive','active');
    this._RouterLinkWithHref_7_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._RouterLinkActive_7_4 = new import12.RouterLinkActive(this.parentInjector.get(import15.Router),new import18.ElementRef(this._el_7),this.renderer);
    this._query_RouterLink_7_0 = new import14.QueryList<any>();
    this._query_RouterLinkWithHref_7_1 = new import14.QueryList<any>();
    this._text_8 = this.renderer.createText(this._el_7,'Default',this.debug(8,3,53));
    this._text_9 = this.renderer.createText(this._el_4,'\n      ',this.debug(9,3,69));
    this._el_10 = this.renderer.createElement(this._el_4,'li',this.debug(10,4,6));
    this._el_11 = this.renderer.createElement(this._el_10,'a',this.debug(11,4,10));
    this.renderer.setElementAttribute(this._el_11,'routerLink','app');
    this.renderer.setElementAttribute(this._el_11,'routerLinkActive','active');
    this._RouterLinkWithHref_11_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._RouterLinkActive_11_4 = new import12.RouterLinkActive(this.parentInjector.get(import15.Router),new import18.ElementRef(this._el_11),this.renderer);
    this._query_RouterLink_11_0 = new import14.QueryList<any>();
    this._query_RouterLinkWithHref_11_1 = new import14.QueryList<any>();
    this._text_12 = this.renderer.createText(this._el_11,'App Component',this.debug(12,4,56));
    this._text_13 = this.renderer.createText(this._el_4,'\n      ',this.debug(13,4,78));
    this._el_14 = this.renderer.createElement(this._el_4,'li',this.debug(14,5,6));
    this._el_15 = this.renderer.createElement(this._el_14,'a',this.debug(15,5,10));
    this.renderer.setElementAttribute(this._el_15,'routerLink','a/a');
    this.renderer.setElementAttribute(this._el_15,'routerLinkActive','active');
    this._RouterLinkWithHref_15_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._RouterLinkActive_15_4 = new import12.RouterLinkActive(this.parentInjector.get(import15.Router),new import18.ElementRef(this._el_15),this.renderer);
    this._query_RouterLink_15_0 = new import14.QueryList<any>();
    this._query_RouterLinkWithHref_15_1 = new import14.QueryList<any>();
    this._text_16 = this.renderer.createText(this._el_15,'A Component',this.debug(16,5,56));
    this._text_17 = this.renderer.createText(this._el_4,'\n      ',this.debug(17,5,76));
    this._el_18 = this.renderer.createElement(this._el_4,'li',this.debug(18,6,6));
    this._el_19 = this.renderer.createElement(this._el_18,'a',this.debug(19,6,10));
    this.renderer.setElementAttribute(this._el_19,'routerLink','b');
    this.renderer.setElementAttribute(this._el_19,'routerLinkActive','active');
    this._RouterLinkWithHref_19_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._RouterLinkActive_19_4 = new import12.RouterLinkActive(this.parentInjector.get(import15.Router),new import18.ElementRef(this._el_19),this.renderer);
    this._query_RouterLink_19_0 = new import14.QueryList<any>();
    this._query_RouterLinkWithHref_19_1 = new import14.QueryList<any>();
    this._text_20 = this.renderer.createText(this._el_19,'B Component',this.debug(20,6,54));
    this._text_21 = this.renderer.createText(this._el_4,'\n      ',this.debug(21,6,74));
    this._el_22 = this.renderer.createElement(this._el_4,'li',this.debug(22,7,6));
    this._el_23 = this.renderer.createElement(this._el_22,'a',this.debug(23,7,10));
    this.renderer.setElementAttribute(this._el_23,'routerLink','c');
    this.renderer.setElementAttribute(this._el_23,'routerLinkActive','active');
    this._RouterLinkWithHref_23_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._RouterLinkActive_23_4 = new import12.RouterLinkActive(this.parentInjector.get(import15.Router),new import18.ElementRef(this._el_23),this.renderer);
    this._query_RouterLink_23_0 = new import14.QueryList<any>();
    this._query_RouterLinkWithHref_23_1 = new import14.QueryList<any>();
    this._text_24 = this.renderer.createText(this._el_23,'C Component',this.debug(24,7,54));
    this._text_25 = this.renderer.createText(this._el_4,'\n      ',this.debug(25,7,74));
    this._el_26 = this.renderer.createElement(this._el_4,'li',this.debug(26,8,6));
    this._el_27 = this.renderer.createElement(this._el_26,'a',this.debug(27,8,10));
    this.renderer.setElementAttribute(this._el_27,'routerLink','xxx');
    this.renderer.setElementAttribute(this._el_27,'routerLinkActive','active');
    this._RouterLinkWithHref_27_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._RouterLinkActive_27_4 = new import12.RouterLinkActive(this.parentInjector.get(import15.Router),new import18.ElementRef(this._el_27),this.renderer);
    this._query_RouterLink_27_0 = new import14.QueryList<any>();
    this._query_RouterLinkWithHref_27_1 = new import14.QueryList<any>();
    this._text_28 = this.renderer.createText(this._el_27,'Non Component',this.debug(28,8,56));
    this._text_29 = this.renderer.createText(this._el_4,'\n    ',this.debug(29,8,78));
    this._text_30 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(30,9,9));
    this._el_31 = this.renderer.createElement(parentRenderNode,'router-outlet',this.debug(31,10,4));
    this._appEl_31 = new import4.AppElement(31,(null as any),this,this._el_31);
    this._RouterOutlet_31_5 = new import13.RouterOutlet(this.parentInjector.get(import19.RouterOutletMap),this._appEl_31.vcRef,this.parentInjector.get(import20.ComponentFactoryResolver),(null as any));
    this._text_32 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(32,10,35));
    var disposable_0:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    this._expr_9 = import8.UNINITIALIZED;
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    this._expr_13 = import8.UNINITIALIZED;
    this._expr_14 = import8.UNINITIALIZED;
    this._expr_15 = import8.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_23,'click',this.eventHandler(this._handle_click_23_0.bind(this)));
    this._expr_17 = import8.UNINITIALIZED;
    this._expr_18 = import8.UNINITIALIZED;
    this._expr_19 = import8.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_27,'click',this.eventHandler(this._handle_click_27_0.bind(this)));
    this._expr_21 = import8.UNINITIALIZED;
    this._expr_22 = import8.UNINITIALIZED;
    this._expr_23 = import8.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.RouterLinkWithHref) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._RouterLinkWithHref_7_3; }
    if (((token === import12.RouterLinkActive) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._RouterLinkActive_7_4; }
    if (((token === import11.RouterLinkWithHref) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkWithHref_11_3; }
    if (((token === import12.RouterLinkActive) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkActive_11_4; }
    if (((token === import11.RouterLinkWithHref) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkWithHref_15_3; }
    if (((token === import12.RouterLinkActive) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkActive_15_4; }
    if (((token === import11.RouterLinkWithHref) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._RouterLinkWithHref_19_3; }
    if (((token === import12.RouterLinkActive) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._RouterLinkActive_19_4; }
    if (((token === import11.RouterLinkWithHref) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._RouterLinkWithHref_23_3; }
    if (((token === import12.RouterLinkActive) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._RouterLinkActive_23_4; }
    if (((token === import11.RouterLinkWithHref) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._RouterLinkWithHref_27_3; }
    if (((token === import12.RouterLinkActive) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._RouterLinkActive_27_4; }
    if (((token === import13.RouterOutlet) && (31 === requestNodeIndex))) { return this._RouterOutlet_31_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    this.debug(7,3,10);
    changes = (null as any);
    this.debug(7,3,13);
    const currVal_1:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_7_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_7_3.ngOnChanges(changes); }
    this.debug(7,3,10);
    changes = (null as any);
    this.debug(7,3,27);
    const currVal_3:any = 'active';
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._RouterLinkActive_7_4.routerLinkActive = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import8.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_7_4.ngOnChanges(changes); }
    this.debug(11,4,10);
    changes = (null as any);
    this.debug(11,4,13);
    const currVal_5:any = 'app';
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._RouterLinkWithHref_11_3.routerLink = currVal_5;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_11_3.ngOnChanges(changes); }
    this.debug(11,4,10);
    changes = (null as any);
    this.debug(11,4,30);
    const currVal_7:any = 'active';
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._RouterLinkActive_11_4.routerLinkActive = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import8.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_11_4.ngOnChanges(changes); }
    this.debug(15,5,10);
    changes = (null as any);
    this.debug(15,5,13);
    const currVal_9:any = 'a/a';
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._RouterLinkWithHref_15_3.routerLink = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_15_3.ngOnChanges(changes); }
    this.debug(15,5,10);
    changes = (null as any);
    this.debug(15,5,30);
    const currVal_11:any = 'active';
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._RouterLinkActive_15_4.routerLinkActive = currVal_11;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import8.SimpleChange(this._expr_11,currVal_11);
      this._expr_11 = currVal_11;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_15_4.ngOnChanges(changes); }
    this.debug(19,6,10);
    changes = (null as any);
    this.debug(19,6,13);
    const currVal_13:any = 'b';
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._RouterLinkWithHref_19_3.routerLink = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_19_3.ngOnChanges(changes); }
    this.debug(19,6,10);
    changes = (null as any);
    this.debug(19,6,28);
    const currVal_15:any = 'active';
    if (import5.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._RouterLinkActive_19_4.routerLinkActive = currVal_15;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import8.SimpleChange(this._expr_15,currVal_15);
      this._expr_15 = currVal_15;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_19_4.ngOnChanges(changes); }
    this.debug(23,7,10);
    changes = (null as any);
    this.debug(23,7,13);
    const currVal_17:any = 'c';
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._RouterLinkWithHref_23_3.routerLink = currVal_17;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_17,currVal_17);
      this._expr_17 = currVal_17;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_23_3.ngOnChanges(changes); }
    this.debug(23,7,10);
    changes = (null as any);
    this.debug(23,7,28);
    const currVal_19:any = 'active';
    if (import5.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._RouterLinkActive_23_4.routerLinkActive = currVal_19;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import8.SimpleChange(this._expr_19,currVal_19);
      this._expr_19 = currVal_19;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_23_4.ngOnChanges(changes); }
    this.debug(27,8,10);
    changes = (null as any);
    this.debug(27,8,13);
    const currVal_21:any = 'xxx';
    if (import5.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._RouterLinkWithHref_27_3.routerLink = currVal_21;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_21,currVal_21);
      this._expr_21 = currVal_21;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_27_3.ngOnChanges(changes); }
    this.debug(27,8,10);
    changes = (null as any);
    this.debug(27,8,30);
    const currVal_23:any = 'active';
    if (import5.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._RouterLinkActive_27_4.routerLinkActive = currVal_23;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import8.SimpleChange(this._expr_23,currVal_23);
      this._expr_23 = currVal_23;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_27_4.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_7_0.dirty) {
        this._query_RouterLink_7_0.reset([]);
        this._RouterLinkActive_7_4.links = this._query_RouterLink_7_0;
        this._query_RouterLink_7_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_7_1.dirty) {
        this._query_RouterLinkWithHref_7_1.reset([this._RouterLinkWithHref_7_3]);
        this._RouterLinkActive_7_4.linksWithHrefs = this._query_RouterLinkWithHref_7_1;
        this._query_RouterLinkWithHref_7_1.notifyOnChanges();
      }
      if (this._query_RouterLink_11_0.dirty) {
        this._query_RouterLink_11_0.reset([]);
        this._RouterLinkActive_11_4.links = this._query_RouterLink_11_0;
        this._query_RouterLink_11_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_11_1.dirty) {
        this._query_RouterLinkWithHref_11_1.reset([this._RouterLinkWithHref_11_3]);
        this._RouterLinkActive_11_4.linksWithHrefs = this._query_RouterLinkWithHref_11_1;
        this._query_RouterLinkWithHref_11_1.notifyOnChanges();
      }
      if (this._query_RouterLink_15_0.dirty) {
        this._query_RouterLink_15_0.reset([]);
        this._RouterLinkActive_15_4.links = this._query_RouterLink_15_0;
        this._query_RouterLink_15_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_15_1.dirty) {
        this._query_RouterLinkWithHref_15_1.reset([this._RouterLinkWithHref_15_3]);
        this._RouterLinkActive_15_4.linksWithHrefs = this._query_RouterLinkWithHref_15_1;
        this._query_RouterLinkWithHref_15_1.notifyOnChanges();
      }
      if (this._query_RouterLink_19_0.dirty) {
        this._query_RouterLink_19_0.reset([]);
        this._RouterLinkActive_19_4.links = this._query_RouterLink_19_0;
        this._query_RouterLink_19_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_19_1.dirty) {
        this._query_RouterLinkWithHref_19_1.reset([this._RouterLinkWithHref_19_3]);
        this._RouterLinkActive_19_4.linksWithHrefs = this._query_RouterLinkWithHref_19_1;
        this._query_RouterLinkWithHref_19_1.notifyOnChanges();
      }
      if (this._query_RouterLink_23_0.dirty) {
        this._query_RouterLink_23_0.reset([]);
        this._RouterLinkActive_23_4.links = this._query_RouterLink_23_0;
        this._query_RouterLink_23_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_23_1.dirty) {
        this._query_RouterLinkWithHref_23_1.reset([this._RouterLinkWithHref_23_3]);
        this._RouterLinkActive_23_4.linksWithHrefs = this._query_RouterLinkWithHref_23_1;
        this._query_RouterLinkWithHref_23_1.notifyOnChanges();
      }
      if (this._query_RouterLink_27_0.dirty) {
        this._query_RouterLink_27_0.reset([]);
        this._RouterLinkActive_27_4.links = this._query_RouterLink_27_0;
        this._query_RouterLink_27_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_27_1.dirty) {
        this._query_RouterLinkWithHref_27_1.reset([this._RouterLinkWithHref_27_3]);
        this._RouterLinkActive_27_4.linksWithHrefs = this._query_RouterLinkWithHref_27_1;
        this._query_RouterLinkWithHref_27_1.notifyOnChanges();
      }
      this.debug(7,3,10);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_7_4.ngAfterContentInit(); }
      this.debug(11,4,10);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_11_4.ngAfterContentInit(); }
      this.debug(15,5,10);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_15_4.ngAfterContentInit(); }
      this.debug(19,6,10);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_19_4.ngAfterContentInit(); }
      this.debug(23,7,10);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_23_4.ngAfterContentInit(); }
      this.debug(27,8,10);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_27_4.ngAfterContentInit(); }
    }
    this.debug(7,3,10);
    const currVal_2:any = this._RouterLinkWithHref_7_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_7,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.debug(11,4,10);
    const currVal_6:any = this._RouterLinkWithHref_11_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_11,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_6));
      this._expr_6 = currVal_6;
    }
    this.debug(15,5,10);
    const currVal_10:any = this._RouterLinkWithHref_15_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementProperty(this._el_15,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_10));
      this._expr_10 = currVal_10;
    }
    this.debug(19,6,10);
    const currVal_14:any = this._RouterLinkWithHref_19_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementProperty(this._el_19,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_14));
      this._expr_14 = currVal_14;
    }
    this.debug(23,7,10);
    const currVal_18:any = this._RouterLinkWithHref_23_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementProperty(this._el_23,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_18));
      this._expr_18 = currVal_18;
    }
    this.debug(27,8,10);
    const currVal_22:any = this._RouterLinkWithHref_27_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementProperty(this._el_27,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_22));
      this._expr_22 = currVal_22;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(7,3,10);
    this._RouterLinkWithHref_7_3.ngOnDestroy();
    this._RouterLinkActive_7_4.ngOnDestroy();
    this.debug(11,4,10);
    this._RouterLinkWithHref_11_3.ngOnDestroy();
    this._RouterLinkActive_11_4.ngOnDestroy();
    this.debug(15,5,10);
    this._RouterLinkWithHref_15_3.ngOnDestroy();
    this._RouterLinkActive_15_4.ngOnDestroy();
    this.debug(19,6,10);
    this._RouterLinkWithHref_19_3.ngOnDestroy();
    this._RouterLinkActive_19_4.ngOnDestroy();
    this.debug(23,7,10);
    this._RouterLinkWithHref_23_3.ngOnDestroy();
    this._RouterLinkActive_23_4.ngOnDestroy();
    this.debug(27,8,10);
    this._RouterLinkWithHref_27_3.ngOnDestroy();
    this._RouterLinkActive_27_4.ngOnDestroy();
    this.debug(31,10,4);
    this._RouterOutlet_31_5.ngOnDestroy();
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(7,3,10);
    const pd_0:any = ((<any>this._RouterLinkWithHref_7_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(11,4,10);
    const pd_0:any = ((<any>this._RouterLinkWithHref_11_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(15,5,10);
    const pd_0:any = ((<any>this._RouterLinkWithHref_15_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(19,6,10);
    const pd_0:any = ((<any>this._RouterLinkWithHref_19_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(23,7,10);
    const pd_0:any = ((<any>this._RouterLinkWithHref_23_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(27,8,10);
    const pd_0:any = ((<any>this._RouterLinkWithHref_27_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AppComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('/Users/albatrosary/Sandbox/angular2-lite-start/src/scripts/app.component.ts class AppComponent - inline template',0,import9.ViewEncapsulation.None,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_DefaultComponent_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.DefaultComponent],import1.DefaultComponent,{})];
var renderType_DefaultComponent_Host:import2.RenderComponentType = (null as any);
class _View_DefaultComponent_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _DefaultComponent_0_4:import1.DefaultComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_DefaultComponent_Host0,renderType_DefaultComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_DefaultComponent_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-default',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_DefaultComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DefaultComponent_0_4 = new import1.DefaultComponent();
    this._appEl_0.initComponent(this._DefaultComponent_0_4,[],compView_0);
    compView_0.create(this._DefaultComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.DefaultComponent) && (0 === requestNodeIndex))) { return this._DefaultComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_DefaultComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_DefaultComponent_Host === (null as any))) { (renderType_DefaultComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_DefaultComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const DefaultComponentNgFactory:import10.ComponentFactory<import1.DefaultComponent> = new import10.ComponentFactory<import1.DefaultComponent>('my-default',viewFactory_DefaultComponent_Host0,import1.DefaultComponent);
const styles_DefaultComponent:any[] = [];
const nodeDebugInfos_DefaultComponent0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_DefaultComponent:import2.RenderComponentType = (null as any);
class _View_DefaultComponent0 extends import3.DebugAppView<import1.DefaultComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_DefaultComponent0,renderType_DefaultComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_DefaultComponent0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(0,0,0));
    this._el_1 = this.renderer.createElement(parentRenderNode,'h1',this.debug(1,1,4));
    this._text_2 = this.renderer.createText(this._el_1,'Default',this.debug(2,1,8));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(3,1,20));
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_DefaultComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.DefaultComponent> {
  if ((renderType_DefaultComponent === (null as any))) { (renderType_DefaultComponent = viewUtils.createRenderComponentType('/Users/albatrosary/Sandbox/angular2-lite-start/src/scripts/app.component.ts class DefaultComponent - inline template',0,import9.ViewEncapsulation.None,styles_DefaultComponent,{})); }
  return new _View_DefaultComponent0(viewUtils,parentInjector,declarationEl);
}