/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from './pagenotfound.component';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
const nodeDebugInfos_PageNotFoundComponent_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.PageNotFoundComponent],import1.PageNotFoundComponent,{})];
var renderType_PageNotFoundComponent_Host:import2.RenderComponentType = (null as any);
class _View_PageNotFoundComponent_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _PageNotFoundComponent_0_4:import1.PageNotFoundComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_PageNotFoundComponent_Host0,renderType_PageNotFoundComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_PageNotFoundComponent_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-page-not-found',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PageNotFoundComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PageNotFoundComponent_0_4 = new import1.PageNotFoundComponent();
    this._appEl_0.initComponent(this._PageNotFoundComponent_0_4,[],compView_0);
    compView_0.create(this._PageNotFoundComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.PageNotFoundComponent) && (0 === requestNodeIndex))) { return this._PageNotFoundComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_PageNotFoundComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_PageNotFoundComponent_Host === (null as any))) { (renderType_PageNotFoundComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_PageNotFoundComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const PageNotFoundComponentNgFactory:import10.ComponentFactory<import1.PageNotFoundComponent> = new import10.ComponentFactory<import1.PageNotFoundComponent>('my-page-not-found',viewFactory_PageNotFoundComponent_Host0,import1.PageNotFoundComponent);
const styles_PageNotFoundComponent:any[] = [];
const nodeDebugInfos_PageNotFoundComponent0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_PageNotFoundComponent:import2.RenderComponentType = (null as any);
class _View_PageNotFoundComponent0 extends import3.DebugAppView<import1.PageNotFoundComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_PageNotFoundComponent0,renderType_PageNotFoundComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_PageNotFoundComponent0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(0,0,0));
    this._el_1 = this.renderer.createElement(parentRenderNode,'h1',this.debug(1,1,4));
    this._text_2 = this.renderer.createText(this._el_1,'Page Not Found',this.debug(2,1,8));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(3,1,27));
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_PageNotFoundComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.PageNotFoundComponent> {
  if ((renderType_PageNotFoundComponent === (null as any))) { (renderType_PageNotFoundComponent = viewUtils.createRenderComponentType('/Users/albatrosary/Sandbox/angular2-lite-start/src/scripts/pagenotfound.component.ts class PageNotFoundComponent - inline template',0,import9.ViewEncapsulation.None,styles_PageNotFoundComponent,{})); }
  return new _View_PageNotFoundComponent0(viewUtils,parentInjector,declarationEl);
}